### ISSUE TITLE
AttributeError: 'User' object has no attribute 'spawner' when EIN tries to authenticate with JupyterHub

### ISSUE THREAD

**Issue by millejoh** [jupyterhub/jupyterhub#1261]
At the moment I am using the REST API as documented on the website
(https://jupyterhub.readthedocs.io/en/latest/_static/rest-api/index.html)
and things go pretty well, up to a certain point. Here is the sequence of events I have programmed:

 1. After supplying a url, user name, and password, ein sends a query to '/hub/api/authorizations/token'.
 2. We store the token, make sure the Authorization header looks like the example code at (https://jupyterhub.readthedocs.io/en/latest/rest.html) then query '/hub/api/user/[user]/server' to start a notebook server.
 3. EIN queries '/hub/api/user/[user]' to get information about this user, most importantly we are looking for the server path for the newly started server.
 4. Use the server path to use EIN's usual facilities for accessing the notebook server.

Everything goes well up until step 4. On using the server path to make a content API call I get the following output in the terminal running jupyterhub (which I am start with a simple call to `jupyterhub`). The URL for the content API call looks something like `/hub/user/[username]/api/contents`.

```
[E 2017-07-22 10:05:45.125 JupyterHub web:1590] Uncaught exception GET /hub/user/millejoh/api/contents/ (::ffff:127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/hub/user/millejoh/api/contents/', version='HTTP/1.1', remote_ip='::ffff:127.0.0.1', headers={'X-Forwarded-Host': '127.0.0.1:8000',
'X-Forwarded-Proto': 'http', 'X-Forwarded-Port': '8000', 'X-Forwarded-For':
'::ffff:127.0.0.1', 'Authorization': 'token bb5e49ad68dc4f5abdaccd954abb8742', 'X-Xsrftoken':
'2|d136b4d2|ee8d84ef6c536241a6e09c36453a9328|1497490250', 'Cookie':
'_xsrf=2|d136b4d2|ee8d84ef6c536241a6e09c36453a9328|1497490250',
'Accept-Encoding': 'deflate, gzip', 'Accept': '*/*', 'User-Agent':
'curl/7.54.0', 'Host': '127.0.0.1:8000', 'Connection': 'close'})
    Traceback (most recent call last):
      File
"/home/millejoh/miniconda3/envs/jupyterhub/lib/python3.6/site-packages/torna
do/web.py", line 1511, in _execute
        result = yield result
      File
"/home/millejoh/miniconda3/envs/jupyterhub/lib/python3.6/site-packages/jupyt
erhub/handlers/base.py", line 520, in get
        if current_user.spawner:
    AttributeError: 'User' object has no attribute 'spawner'

[E 2017-07-22 10:05:45.223 JupyterHub log:99] {
      "X-Forwarded-Host": "127.0.0.1:8000",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "8000",
      "X-Forwarded-For": "::ffff:127.0.0.1",
      "Authorization": "token [secret]",
      "X-Xsrftoken":
"2|d136b4d2|ee8d84ef6c536241a6e09c36453a9328|1497490250",
      "Cookie":
"_xsrf=2|d136b4d2|ee8d84ef6c536241a6e09c36453a9328|1497490250",
      "Accept-Encoding": "deflate, gzip",
      "Accept": "*/*",
      "User-Agent": "curl/7.54.0",
      "Host": "127.0.0.1:8000",
      "Connection": "close"
    }
[E 2017-07-22 10:05:45.225 JupyterHub log:100] 500 GET /hub/user/millejoh/api/contents/ (millejoh@::ffff:127.0.0.1) 96.56ms
```

The rest of the output looks like the following:

```
[I 2017-07-24 12:48:21.497 JupyterHub app:724] Loading cookie_secret from /home/millejoh/jupyterhub_cookie_secret
[W 2017-07-24 12:48:21.547 JupyterHub app:365]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[W 2017-07-24 12:48:21.553 JupyterHub app:864] No admin users, admin interface will be unavailable.
[W 2017-07-24 12:48:21.554 JupyterHub app:865] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2017-07-24 12:48:21.554 JupyterHub app:892] Not using whitelist. Any authenticated user will be allowed.
[I 2017-07-24 12:48:21.583 JupyterHub app:1453] Hub API listening on http://127.0.0.1:8081/hub/
[W 2017-07-24 12:48:23.597 JupyterHub app:1174] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2017-07-24 12:48:23.598 JupyterHub app:1176] Starting proxy @ http://*:8000/
12:48:23.895 - info: [ConfigProxy] Adding route / -> http://127.0.0.1:8081
12:48:23.903 - info: [ConfigProxy] Proxying http://*:8000 to http://127.0.0.1:8081
12:48:23.904 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[I 2017-07-24 12:48:24.128 JupyterHub app:1485] JupyterHub is now running at http://127.0.0.1:8000/
[I 2017-07-24 12:49:26.151 millejoh notebookapp:1367] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2017-07-24 12:49:26.573 millejoh log:47] 302 GET /user/millejoh (127.0.0.1) 3.67ms
[I 2017-07-24 12:49:26.579 JupyterHub base:322] User millejoh server took 2.381 seconds to start
[I 2017-07-24 12:49:26.580 JupyterHub orm:188] Adding user millejoh to proxy /user/millejoh => http://127.0.0.1:52915
12:49:26.590 - info: [ConfigProxy] Adding route /user/millejoh -> http://127.0.0.1:52915
12:49:26.592 - info: [ConfigProxy] 201 POST /api/routes/user/millejoh
[I 2017-07-24 12:49:26.611 JupyterHub log:100] 201 POST /hub/api/users/millejoh/server (millejoh@::ffff:127.0.0.1) 2408.52ms
[I 2017-07-24 12:49:26.728 JupyterHub log:100] 200 GET /hub/api/users/millejoh (millejoh@::ffff:127.0.0.1) 15.12ms
[I 2017-07-24 12:49:26.902 millejoh log:47] 302 GET /user/millejoh/api/contents/ (::ffff:127.0.0.1) 1.07ms
[W 2017-07-24 12:49:26.913 JupyterHub pages:41] Redirecting /hub/?next=%2Fuser%2Fmillejoh%2Fapi%2Fcontents%2F to /hub/user/millejoh/api/contents/. For sharing public links, use /user-redirect/
[I 2017-07-24 12:49:26.925 JupyterHub log:100] 302 GET /hub/?next=%2Fuser%2Fmillejoh%2Fapi%2Fcontents%2F (millejoh@::ffff:127.0.0.1) 6.32ms
[E 2017-07-24 12:49:26.938 JupyterHub web:1590] Uncaught exception GET /hub/user/millejoh/api/contents/ (::ffff:127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8000', method='GET', uri='/hub/user/millejoh/api/contents/', version='HTTP/1.1', remote_ip='::ffff:127.0.0.1', headers={'X-Forwarded-Host': '127.0.0.1:8000', 'X-Forwarded-Proto': 'http', 'X-Forwarded-Port': '8000', 'X-Forwarded-For': '::ffff:127.0.0.1', 'Authorization': 'token b71cbe1c1f3f441f9fa91aa5db6b8cf0', 'X-Xsrftoken': '2|d136b4d2|ee8d84ef6c536241a6e09c36453a9328|1497490250', 'Cookie': '_xsrf=2|d136b4d2|ee8d84ef6c536241a6e09c36453a9328|1497490250', 'Accept-Encoding': 'deflate, gzip', 'Accept': '*/*', 'User-Agent': 'curl/7.54.0', 'Host': '127.0.0.1:8000', 'Connection': 'close'})
    Traceback (most recent call last):
      File "/home/millejoh/miniconda3/envs/jupyterhub/lib/python3.6/site-packages/tornado/web.py", line 1511, in _execute
        result = yield result
      File "/home/millejoh/miniconda3/envs/jupyterhub/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 520, in get
        if current_user.spawner:
    AttributeError: 'User' object has no attribute 'spawner'

[E 2017-07-24 12:49:27.004 JupyterHub log:99] {
      "X-Forwarded-Host": "127.0.0.1:8000",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "8000",
      "X-Forwarded-For": "::ffff:127.0.0.1",
      "Authorization": "token [secret]",
      "X-Xsrftoken": "2|d136b4d2|ee8d84ef6c536241a6e09c36453a9328|1497490250",
      "Cookie": "_xsrf=2|d136b4d2|ee8d84ef6c536241a6e09c36453a9328|1497490250",
      "Accept-Encoding": "deflate, gzip",
      "Accept": "*/*",
      "User-Agent": "curl/7.54.0",
      "Host": "127.0.0.1:8000",
      "Connection": "close"
    }
[E 2017-07-24 12:49:27.007 JupyterHub log:100] 500 GET /hub/user/millejoh/api/contents/ (millejoh@::ffff:127.0.0.1) 65.07ms
```

**Comment by minrk** [comment]
The error is a bug in 0.7 that I believe is fixed in master, where requests authenticated with a user token do not return the right object.

But in general, token-authenticated requests to single-user servers doesn't work in JupyterHub 0.7. That feature has been implemented in master, but wasn't in 0.7, which predated token auth support in jupyter/notebook. My guess is that this is the problem:

> 302 GET /user/millejoh/api/contents/ (::ffff:127.0.0.1) 1.07ms

because I suspect you are making a request to the single-user server with `Authentication: token ...`, and that's not going to work in 0.7. It should in master, though.


This script is my interpretation of your steps in Python, and it works against master (not 0.7): https://gist.github.com/3045784d928a98c445ed997cb6b55c62

**Comment by millejoh** [comment]
@minrk, tested against master and things are working. Thanks for the sample code, it helped get my code in line.

At the moment all is working well until I try to open a websocket, at which point I get a "couldn't authenticate WebSocket connection."

The websocket protocol is a bit different, so I'm not sure what I'm missing. I can try reading the notebook ui code to see how it sets up the websocket connect, but if you have some thoughts it might save me some time - especially since I don't know javascript too well.

Thanks for the help!

**Comment by millejoh** [comment]
Never mind, figured it out! It works! Life is good again...

**Comment by willingc** [comment]
We're glad @millejoh. Thanks for sharing your success.
