### ISSUE TITLE
Admin user cannot access jupyter user rest api through hub

### ISSUE THREAD

**Issue by ghazpar** [jupyterhub/jupyterhub#1147]
**How to reproduce the issue**
I have set the following in my jupyterhub config file (amongst other things):
```
c.Authenticator.admin_users = {'apache'}
c.Jupyterhub.admin_access = True
```
The apache user runs the following requests code:
```
headers = {
    'Authorization': 'token {}'.format(settings.JPY_API_TOKEN),
    'Referer': 'http://localhost:8081/hub',
}
r = requests.get(
    'http://localhost:8081/hub/user/{}/api/sessions/'.format(user),
    headers=headers, timeout=5
)
```
The `settings.JPY_API_TOKEN` token is valid for user apache (it works for other API calls). 

**What you expected to happen**
I am expecting that `r.json()` would return the sessions of user `user` (which happens to be `mapar9` below).

**What actually happens**
I get a server error (500) with the following log:
```
[E 2017-05-22 15:05:32.641 JupyterHub web:1590] Uncaught exception GET /hub/user/mapar9/api/sessions/ (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8081', method='GET', uri='/hub/user/mapar9/api/sessions/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Referer': 'http://localhost:8081/hub', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Host': 'localhost:8081', 'Connection': 'keep-alive', 'Authorization': 'token [valid apache token]', 'User-Agent': 'python-requests/2.14.2'})
    Traceback (most recent call last):
      File "/opt/anaconda-3-4.0.0/lib/python3.5/site-packages/tornado/web.py", line 1511, in _execute
        result = yield result
      File "/opt/anaconda-3-4.0.0/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 547, in get
        target = url_path_join(current_user.url, user_path or '')
    AttributeError: 'User' object has no attribute 'url'

[E 2017-05-22 15:05:32.661 JupyterHub log:99] {
      "Referer": "http://localhost:8081/hub",
      "Accept-Encoding": "gzip, deflate",
      "Accept": "*/*",
      "Host": "localhost:8081",
      "Connection": "keep-alive",
      "Authorization": "token [secret]",
      "User-Agent": "python-requests/2.14.2"
    }
[E 2017-05-22 15:05:32.661 JupyterHub log:100] 500 GET /hub/user/mapar9/api/sessions/ (apache@127.0.0.1) 25.11ms
```
**Share what version of JupyterHub you are using**
```
jupyterhub --version
0.7.2
```

Am I doing something wrong? In any case, I think my request should not produce an error 500!

**Comment by minrk** [comment]
Two things related to this have been fixed in master:

1. admin_access only grants *cookie*-based authorization for administrators to single-user servers, not API keys in 0.7 (admin tokens work in 0.8)
2. the failed authentication redirects you through to the for-humans user spawn page, which it doesn't do anymore (hence the 500 error, which should have been handled as 400).

**Comment by ghazpar** [comment]
Ok thanks. So you are saying that my code should work with release 0.8? Do you have an idea of when 0.8 will be released?
